---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---
```{r pkg-knitr-opts, include=FALSE}
hrbrpkghelpr::global_opts()
```

```{r badges, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::stinking_badges()
```

```{r description, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::yank_title_and_description()
```

## What's Inside The Tin

The following functions are implemented:

```{r ingredients, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::describe_ingredients()
```

## Installation

```{r install-ex, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::install_block()
```

## Usage

```{r lib-ex}
library(nanoid)

# current version
packageVersion("nanoid")

```

```{r ex-01}
NANOIDgenerate()

NANOIDgenerate(alphabet = nanoid_dict[["numbers"]])

NANOIDgenerate(alphabet = nanoid_dict[["lowercase"]])

NANOIDgenerate(alphabet = nanoid_dict[["uppercase"]])

NANOIDgenerate(alphabet = nanoid_dict[["hexadecimal_lowercase"]])

NANOIDgenerate(alphabet = nanoid_dict[["hexadecimal_uppercase"]])

NANOIDgenerate(alphabet = nanoid_dict[["nolookalikes"]])

NANOIDgenerate(alphabet = nanoid_dict[["nolookalikes_safe"]])

NANOIDgenerate(alphabet = nanoid_dict[["alphanumeric"]])
```

```{r ex-02}
NANOIDgenerate(size = 10)

NANOIDgenerate(size = 10, alphabet = nanoid_dict[["numbers"]])

NANOIDgenerate(size = 10, alphabet = nanoid_dict[["lowercase"]])

NANOIDgenerate(size = 10, alphabet = nanoid_dict[["uppercase"]])

NANOIDgenerate(size = 10, alphabet = nanoid_dict[["hexadecimal_lowercase"]])

NANOIDgenerate(size = 10, alphabet = nanoid_dict[["hexadecimal_uppercase"]])

NANOIDgenerate(size = 10, alphabet = nanoid_dict[["nolookalikes"]])

NANOIDgenerate(size = 10, alphabet = nanoid_dict[["nolookalikes_safe"]])

NANOIDgenerate(size = 10, alphabet = nanoid_dict[["alphanumeric"]])
```

## nanoid Metrics

```{r cloc, echo=FALSE}
cloc::cloc_pkg_md()
```

## Code of Conduct

Please note that this project is released with a Contributor Code of Conduct. 
By participating in this project you agree to abide by its terms.
