// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// int_generate
std::string int_generate(std::string alphabet, std::size_t size);
RcppExport SEXP _nanoid_int_generate(SEXP alphabetSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type alphabet(alphabetSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(int_generate(alphabet, size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nanoid_int_generate", (DL_FUNC) &_nanoid_int_generate, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nanoid(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
