# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
int_generate <- function(alphabet, size) {
    .Call(`_nanoid_int_generate`, alphabet, size)
}

